name: Railstons
favicon: null
layout_spectrum: 0.59149
typography_spectrum: 0.92692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404041'
    - '#ee3c2d'
    - '#ff0000'
    - '#000000'
    - '#ff4000'
  brandStrength: 0.3125
  lightness: 0.24948617117479444
  saturation: 0.5625
  rhythmicContrast: 0.047430698992684484
purpose: []
