name: Railstons
favicon: null
layout_spectrum: 0.59149
typography_spectrum: 0.92692
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Life and Dreams of Ayrton Senna
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#5D636E'
    - '#7E8089'
    - '#151F31'
    - '#ACACB3'
  brandStrength: 0.6971326
  lightness: 0.5358423
  saturation: 0.7168459
  rhythmicContrast: 0.0474307
purpose: []
