name: Railstons
favicon: null
layout_spectrum: 0.5761565403081477
typography_spectrum: 0.9083471386693418
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.265761332353577
  lightness: 0.24948617117479444
  saturation: 0.8440986974164844
  rhythmicContrast: 0.047430698992684484
purpose: []
