favicon: null
name: Railstons
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7168459
  brandStrength: 0.6971326
  lightness: 0.5358423
  brandColors:
    - '#000002'
    - '#5D636E'
    - '#7E8089'
    - '#151F31'
    - '#ACACB3'
  rhythmicContrast: 0.0474307
typography_spectrum: 0.92692
layout_spectrum: 0.59149
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
